<?php

/**
 * @file
 * Contains d8_learn.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function d8_learn_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the d8_learn module.
    case 'help.page.d8_learn':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Learn Drupal 8') . '</p>';
      return $output;

    default:
  }
}

/**
 * implements hook_theme()
 */
function d8_learn_theme() {
  return array(
    // 'weather_widget' => array(
    //   'variables' => array('forums' => NULL, 'topics' => NULL, 'parents' => NULL, 'tid' => NULL, 'sortby' => NULL, 'forum_per_page' => NULL),
    // ),
    // 'forum_list' => array(
    //   'variables' => array('forums' => NULL, 'parents' => NULL, 'tid' => NULL),
    // ),
    // 'forum_icon' => array(
    //   'variables' => array('new_posts' => NULL, 'num_posts' => 0, 'comment_mode' => 0, 'sticky' => 0),
    // ),
    'weather_widget' => array(
      'variables' =>  array('weather_data' => NULL),
    ),
  );
}