<?php

/**
 * @file
 * Contains d8_learn.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function d8_learn_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the d8_learn module.
    case 'help.page.d8_learn':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Learn Drupal 8') . '</p>';
      return $output;

    default:
  }
}
